---
collections:
  - name: community.routeros
#  - name: redhat.rhel_system_roles
#  - name: redhat.satellite
#  - name: redhat.rhel_system_roles
#  - name: chocolatey.chocolatey
#  - name: ansible.windows