---
collections:
  - name: community.routeros
###any of the below throw an error
#  - name: redhat.rhel_system_roles
#  - name: redhat.satellite
#  - name: chocolatey.chocolatey
#  - name: ansible.windows


