---
collections:
  - name: ansible.windows
  - name: ansible.utils
  - name: ansible.posix
  - name: community.routeros
  - name: community.general
  - name: redhat.rhel_system_roles
  - name: redhat.rhel_idm
  - name: redhat.satellite
  - name: fedora.linux_system_roles
  - name: chocolatey.chocolatey
  - name: microsoft.ad

