---
- name: Update Plex RPM for Lifetime PlexPass Member
  hosts: all
  become: yes
  tasks:
  
    - name: Download the latest Plex RPM package
      get_url:
        url: "https://downloads.plex.tv/plex-media-server-new/1.32.0.6918-6f393eda1/redhat/plexmediaserver-1.32.0.6918-6f393eda1.x86_64.rpm"
        #url: "https://plex.tv/downloads/latest/1?channel=16&build=linux-x86_64&distro=redhat"
        dest: "/tmp/plex-ansible-temp.rpm"
        headers:
          "X-Plex-Token": "{{ plexpass_token }}"

    - name: Install the latest Plex RPM package
      yum:
        name: "/tmp/plex-ansible-temp.rpm"
        state: latest
        disable_gpg_check: yes

    - name: Restart the Plex service
      systemd:
        name: plexmediaserver
        state: restarted
