---
- name: Update Plex RPM for Lifetime PlexPass Member
  hosts: all
  become: true
  tasks:

  - name: Download the latest Plex RPM package
    get_url:
      url: "https://downloads.plex.tv/plex-media-server-new/1.32.0.6918-6f393eda1/redhat/plexmediaserver-1.32.0.6918-6f393eda1.x86_64.rpm"
      dest: "/tmp/plex-ansible-temp.rpm"
      headers:
        "X-Plex-Token": "{{ plexpass }}"

  - name: Install Plex RPM package
    yum:
      name: "/tmp/plex-ansible-temp.rpm"
      state: latest
      disable_gpg_check: yes

  - name: Fix permissions of mount point (from media kickstart profile)
    file:
       path: /var/lib/plexmediaserver 
       owner: "plex"
       group: "plex"

  - name: Restart the Plex service
    systemd:
      name: plexmediaserver
      state: restarted
