- name: Mikrotik Backup Device Configuration
  hosts: all
  vars:
  user: admin
  gather_facts: no
  tasks:
   - name: Performing backup of Mikrotik to local storage
     raw: /system backup save name {{inventory_hostname}}

   - name: Exporting current configuration to text
     raw: /export file={{inventory_hostname}}
