---
- hosts: all
  become: true
  tasks:
  - name: Install RHEL/Fedora Web Console (Cockpit)
    include_role:
      name: redhat.rhel_system_roles.cockpit
    vars:
      #cockpit_packages: default
      #cockpit_packages: minimal
      #cockpit_packages: full
      cockpit_packages:
         - cockpit
         - cockpit-bridge
         - cockpit-networkmanager
         - cockpit-bridge
         - cockpit-networkmanager
         - cockpit-packagekit
         - cockpit-selinux
         - cockpit-storaged
         - cockpit-system
         - cockpit-ws
         - cockpit-dashboard
         - cockpit-kdump
         - cockpit-sosreport           
        # - cockpit-machines
        # - cockpit-podman
  - name: Configure Firewall for Web Console
    include_role:
      name: redhat.rhel_system_roles.firewall
    vars:
      firewall:
        service: cockpit
        state: disabled
