---
- hosts: all
  become: true
  tasks:
  - name: Install RHEL/Fedora Cockpit Web Console
    include_role:
      name: redhat.rhel_system_roles.cockpit
    vars:
      #cockpit_packages: default
      #cockpit_packages: minimal
      #cockpit_packages: full
      cockpit_packages:
         - cockpit
         - cockpit-bridge
         - cockpit-networkmanager
         - cockpit-bridge
         - cockpit-networkmanager
         - cockpit-packagekit
         - cockpit-selinux
         - cockpit-storaged
         - cockpit-system
         - cockpit-ws
         - cockpit-kdump
         - cockpit-sosreport
  - name: Install Metrics
    include_role:
      name: redhat.rhel_system_roles.metrics
    vars:
      metrics_retention_days: 7
      metrics_graph_service: true
      metrics_query_service: true

##need to figure out how to create a firewall rule, but not actually start/enable firewalld
#  - name: Configure Firewall for Cockpit Web Console
#    include_role:
#      name: redhat.rhel_system_roles.firewall
#    vars:
#      firewall:
#        service: cockpit
#        state: enabled


##need some way of doing the same on debian below here
