---
- name: Configure OS
  hosts: all
  become: yes
  tasks:
  
    - name: Install various packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - cockpit
        - netdata
        - pcp
        - autofs
        - bash-completion
        - cifs-utils
        - kexec-tools
        - mlocate
        - pcp
        - rsync
        - sysstat
        - tuned
        - cockpit
        - nmap
        - iperf3
        - chrony
#        - auto
#        - sos
#        - deltarpm
#        - chkconfig
#        - ipa-client
        
    - name: Configure chrony and restart it
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        line: 'server 192.168.1.1 iburst'
        state: present
        create: yes
      notify:
        - restart chrony

#    - name: Configure ssh to allow root with content/copy command
#      copy:
#        content: |
#          # Allow root login via SSH, created by ansible
#          PermitRootLogin yes
#        dest: '/etc/ssh/sshd_config.d/enable-root-ssh.conf'
#        mode: '0644'

#    - name: Reload SSH service
#      service:
#        name: sshd
#        state: reloaded

    - name: Use ssh system role to allow root
      include_role:
        name: rhel-system-roles.sshd
      vars:
        sshd:
          PermitRootLogin: yes
          PasswordAuthentication: yes



#    - name: Disable IPv6 via sysctl
#      sysctl:
#        name: net.ipv6.conf.all.disable_ipv6
#        value: 1
#        state: present
#        reload: yes
#
#    - name: Set up automount
#      get_url:
#        url: "{{ item.src }}"
#        dest: "{{ item.dest }}"
#      with_items:
#        - { src: "http://synology.jpriddy.com/kickstart/files/synology.autofs", dest: "/etc/automaster.d/synology.autofs" }
#        - { src: "http://synology.jpriddy.com/kickstart/files/auto.synology", dest: "/etc/auto.synology" }
#        - { src: "http://synology.jpriddy.com/kickstart/files/.synology", dest: "/root/.synology" }
