---
- name: OS Config
  hosts: all
  become: yes
  tasks:
  
  
    - name: Import RPM Fusion gpg keys
      ansible.builtin.rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
        
    - name: Enable the RPM Fusion repository
      dnf:   
        name: "{{ item }}"
        state: present
      with_items:
        - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
        - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
  
    - name: Install some packages...
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - bash-completion
        - mlocate
        - rsync
        - nmap
        - tuned

    - name: Configure sshd to allow root
      include_role:
        name: redhat.rhel_system_roles.sshd
      vars:
        sshd:
          PermitRootLogin: yes

    - name: Configure timesync
      include_role:
        name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: firewall.jpriddy.com
            iburst: true
            
    - name: Configure journald
      include_role:
        name: redhat.rhel_system_roles.journald
      vars:
        journald_persistent: true
        journald_max_disk_size: 512
        journald_per_user: true
        journald_sync_interval: 1
        
    - name: Setup tlog
      include_role:
        name: redhat.rhel_system_roles.tlog
      vars:
        tlog_scope_sssd: all        
        
    - name: Enable and start tuned
      ansible.builtin.service:
        name: tuned
        enabled: yes
        state: started         


#  throws an error but 'succeeds' -- needs to be combined with a kernel change to reserve ram
#
#    - name: Setup kdump
#      include_role:
#        name: redhat.rhel_system_roles.kdump  
#      vars:
#        kdump_path: /var/crash
#        kdump_system_action: reboot
        
