---
- name: OS Config
  hosts: all
  become: yes
  tasks:
  
    - name: Install some packages...
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - bash-completion
        - mlocate
        - rsync
        - nmap

    - name: Configure sshd to allow root
      include_role:
        name: rhel-system-roles.sshd
      vars:
        sshd:
          PermitRootLogin: yes
