---
- name: Install and configure chrony as an NTP client
  hosts: all
  become: yes

  tasks:
    - name: Install chrony
      package:
        name: chrony
        state: latest

    - name: Configure chrony
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        line: 'server 192.168.1.1 iburst'
        state: present
        create: yes
      notify:
        - restart chrony

  handlers:
    - name: restart chrony
      systemd:
        name: chrony
        state: restarted
