---
- name: Install and configure chrony, disable IPv6, set up automount, and install cockpit, netdata, and PCP
  hosts: all
  become: yes

  tasks:
    - name: Install chrony
      package:
        name: chrony
        state: latest

    - name: Configure chrony and restart it
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        line: 'server 192.168.1.1 iburst'
        state: present
        create: yes
      notify:
        - restart chrony

    - name: Disable IPv6 via sysctl
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present
        reload: yes

#    - name: Set up automount
#      get_url:
#        url: "{{ item.src }}"
#        dest: "{{ item.dest }}"
#      with_items:
#        - { src: "http://synology.jpriddy.com/kickstart/files/synology.autofs", dest: "/etc/automaster.d/synology.autofs" }
#        - { src: "http://synology.jpriddy.com/kickstart/files/auto.synology", dest: "/etc/auto.synology" }
#        - { src: "http://synology.jpriddy.com/kickstart/files/.synology", dest: "/root/.synology" }

    - name: Install various packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - cockpit
        - netdata
        - pcp
        - auto
        - autofs
        - bash-completion
        - cifs-utils
        - kexec-tools
        - mlocate
        - pcp
        - rsync
        - sos
        - sysstat
        - tuned
        - deltarpm
        - cockpit
        - chkconfig
        - ipa-client
        - nmap
        - iperf3
#for virtual guests
#qemu-guest-agent

    - name: Add PermitRootLogin to SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?(PermitRootLogin|PermitRootLogin without-password)'
        line: 'PermitRootLogin yes'
      backup: yes

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
