---
- name: OS Config
  hosts: all
  become: yes
  tasks:
  
    - name: Install some packages...
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - bash-completion
        - mlocate
        - rsync
        - nmap
        - tuned

    - name: Configure sshd to allow root
      include_role:
        name: redhat.rhel_system_roles.sshd
      vars:
        sshd:
          PermitRootLogin: yes

    - name: Configure timesync
      include_role:
        name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: firewall.jpriddy.com
            iburst: true
            
    - name: Configure journald
      include_role:
        name: redhat.rhel_system_roles.journald
      vars:
        journald_persistent: true
        journald_max_disk_size: 256
        journald_per_user: true
        journald_sync_interval: 1
        
    - name: Setup tlog
      include_role:
        name: redhat.rhel_system_roles.tlog
      vars:
        tlog_scope_sssd: all
        
        
    - name: Enable and start tuned
      ansible.builtin.service:
        name: tuned
        enabled: yes
        state: started
         
        
#    - name: Setup kdump
#      include_role:
#        name: redhat.rhel_system_roles.kdump  
#      vars:
#        kdump_path: /var/crash
#        kdump_system_action: reboot
        
