---
- hosts: all
  become: true
  tasks:
  - name: Install Metrics
    include_role:
      name: redhat.rhel_system_roles.metrics
    vars:
      metrics_retention_days: 7
      metrics_graph_service: true
      metrics_query_service: true
