---
- name: Network Playbook Test
  gather_facts: false
  hosts: all

  tasks:
- name: Get info from RouterOS devices
  community.routeros.api_facts:
      gather_subset: all

- name: Display some stuff
  debug:
    msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

- name: Retrieve facts
  community.routeros.api_facts:
    - ansible.builtin.debug:
        msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
