- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: yes
  
  tasks:    
    - name: Retrieve facts
      community.routeros.facts:
    - debug:
        msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
