---
- name: Use a routeros command
  hosts: all
  gather_facts: no
  tasks:
  
  - name: Run the command /system reource print
    community.routeros.command:
      commands:
          - /system resource print
    register: system_resource_print
