- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Display Package/OS version
      community.routeros.command:
        commands:
          - /system package print
      register: system_package_print
    - name: Print its output
      debug:
      var: system_package_print.stdout_lines
      
    - name: Retrieve facts
      community.routeros.facts:
    - debug:
        msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
