- name: RouterOS test
  hosts: all
  gather_facts: false

  tasks:

  - name: Display resource statistics (routeros)
    community.routeros.command:
      commands: /system resource print
    register: system_resource_print
  - name: Print its output
    ansible.builtin.debug:
      var: system_resource_print.stdout_lines

  - name: Retrieve facts
    community.routeros.facts:
    - ansible.builtin.debug:
      msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"