- name: RouterOS test with network_cli connection
  hosts: all
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: Display Package/OS version
      routeros_command:
        commands:
          - "/system package print"
      register: system_package_print
    - name: Print its output
      debug: var=system_package_print['stdout_lines']
      
