---
- name: Install 1password-cli
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    
    - name: Create repository file
      dnf_repo:
        name: 1Password Stable Channel
        description: 1password
        baseurl: https://downloads.1password.com/linux/rpm/stable/\$basearch
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    
    
    - name: Import gpg key
      rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present
              
    - name: Install 1password-cli
      dnf:
        name: 1password-cli
        state: latest
