---
- name: Install 1password-cli
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
     
    - name: Import gpg key
      rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present
              
    - name: Install 1password-cli
      dnf:
        name: 1password-cli
        state: latest
