---
- name: Install 1password
  hosts: all
  become: true
  tasks:

   - name: Create 1password repository file
     ansible.builtin.yum_repository:
      name: 1password_ansible
      description: 1Password Stable Channel - Ansible Managed
      baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
      enabled: true
      gpgcheck: true
      gpgkey: https://downloads.1password.com/linux/keys/1password.asc
      state: present

   - name: Import 1password gpg key
     ansible.builtin.rpm_key:
      key: https://downloads.1password.com/linux/keys/1password.asc
      state: present

   - name: Install 1password rpm
     ansible.builtin.package:
      name: 1password
      state: latest
