---
- name: Install 1password
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    
    - name: Create 1password repository file
      yum_repository:
        name: 1password_ansible
        description: 1Password Stable Channel - Ansible Managed
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        enabled: yes
        gpgcheck: yes
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    - name: Import 1password gpg key
      rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present
              
    - name: Install 1password rpm
      dnf:
        name: 1password
        state: latest
