---
- name: OS Config
  gather_facts: yes
  hosts: all
  become: yes
  tasks:
  
    - name: Import RPM Fusion GPG keys...
      rpm_key:
        key: "{{ item }}"
        state: present
      loop:
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
      when: "'Fedora' in ansible_distribution"
      
    - name: ...so that I can install RPM Fusion free and nonfree repos.
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm,https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
        state: present
      when: "'Fedora' in ansible_distribution"
      
    - name: Refresh package cache
      dnf:
        update_cache: yes
  
    - name: Install some other packages...
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - bash-completion
        - mlocate
        - rsync
        - nmap
        - iperf3   ## need to configure this
        - tuned  ## need to configure thie

    - name: Use system role to configure timesync
      include_role:
        name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: firewall.jpriddy.com
            iburst: true
                
        
    - name: Enable and start tuned
      ansible.builtin.service:
        name: tuned
        enabled: yes
        state: started

#CHICKEN AND EGG...  should clean up kickstart before running this
    - name: Use system role to allow root to log into ssh
      include_role:
        name: redhat.rhel_system_roles.sshd
      vars:
        sshd:
          PermitRootLogin: yes
          X11Forwarding: yes

 
    - name: Install guest agent on virtualized hosts
      package:
        name: qemu-guest-agent
        state: present
      when: ansible_virtualization_role == "guest"
 
    - name: Start guest agent service on virtualized hosts
      service:
        name: qemu-guest-agent
        state: started
      when: ansible_virtualization_role == "guest"