---
- name: OS Config
  hosts: all
  become: true
  tasks:

  - name: Install some packages
    package:
      name: "{{ item }}"
      state: latest
      with_items:
        - bash-completion
        - mlocate
        - rsync
        - nmap
        - iperf3
        - tuned

  - name: Use system role to configure timesync
    include_role:
      name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: firewall.jpriddy.com
            iburst: true

  - name: Use system role to configure ssh server
    include_role:
      name: redhat.rhel_system_roles.sshd
      vars:
        sshd_config_owner: root
        sshd_config_group: root
        sshd_config_mode: 600
        sshd_hostkey_owner: root
        sshd_hostkey_group: root
        sshd_hostkey_mode: 600
        sshd:
          PermitRootLogin: yes
          X11Forwarding: yes
          GSSAPIAuthentication: yes
          ChallengeResponseAuthentication: yes
          AllowTcpForwarding: yes

  - name: Install guest agent if virtualized guest
    package:
      name: qemu-guest-agent
      state: latest
    when: ansible_virtualization_role == "guest"

  - name: Start guest agent service if virtualized guest
    service:
      name: qemu-guest-agent
      state: started
      enabled: yes
    when: ansible_virtualization_role == "guest"