---
- name: OS Config
  hosts: all
  become: true
  tasks:

  - name: Install some packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - bash-completion
      - mlocate
      - rsync
      - nmap
      - iperf
      - tuned

  - name: Use system role to configure timesync
    in#clude_role:
      name: redhat.rhel_system_roles.timesync
    vars:
      timesync_ntp_servers:
      - hostname: firewall.jpriddy.com
        iburst: true

  - name: Use system role to configure ssh server
    include_role:
      name: redhat.rhel_system_roles.sshd
    vars:
      sshd_config_owner: root
      sshd_config_group: root
      sshd_config_mode: 0600
      sshd_hostkey_owner: root
      sshd_hostkey_group: root
      sshd_hostkey_mode: 0600
      #sshd_verify_hostkeys: []    # failes to find ssh_keys group without this? 
      sshd_PermitRootLogin: yes
      sshd_X11Forwarding: yes
      sshd_GSSAPIAuthentication: yes
      sshd_ChallengeResponseAuthentication: yes
      sshd_AllowTcpForwarding: yes

  - name: Install guest agent if virtualized guest
    package:
      name: qemu-guest-agent
      state: latest
    when: ansible_virtualization_role == "guest"

  - name: Start guest agent service if virtualized guest
    service:
      name: qemu-guest-agent
      state: started
      enabled: true
    when: ansible_virtualization_role == "guest"
