- name: Update and Restart Containers
  hosts: all
  become: yes

  tasks:
    - name: Update Docker Containers
      become: yes
      loop: "{{ container_info.results }}"
      with_items: "{{ item.containers }}"
      docker_container:
        name: "{{ item.Name }}"
        image: "{{ item.Image }}"
        state: restarted