---
- name: Playbook to unconfigure IPA clients
  hosts: all
  become: true
  gather_facts: yes
  tasks:
  
    - name: Unconfigure ipaclient
      include_role:
         name: freeipa.ansible_freeipa.ipaclient
      vars:
         state: absent

# Ensure host is removed
    - name:  remove host from ipa
      ipahost:
         ipaadmin_password: '{{ ansible_password }}'
         state: absent  
         
