---
- name: Set hostname of server
  hosts: all
  become: true
  tasks:

    - name: Install python bindings so ansible will work
      ansible.builtin.package:
        name: python3-libselinux # required on fedora for ansible to work
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Set hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}.{{ ansible_domain }}'
        use: systemd

    - name: Setup /etc/hostname
      ansible.builtin.copy:
        content: '{{ inventory_hostname }}.{{ ansible_domain }}'
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'
