---
- name: Stop and disable firewall
  hosts: all
  become: true
  tasks:
    - name: Stop and disable the firewalld systemd service
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
