---
- name: Join IdM domain
  hosts: all
  become: yes
  vars:
    ipa_domain: ipa.jpriddy.com
    ipa_server: idm1.ipa.jpriddy.com
    ipa_principal: admin
    
  tasks:
    - name: Ensure ipaclient package is installed...
      package:
        name: ipa-client
        state: present
        
    - name: ...and ensure realmd package is installed for completeness.
      package:
        name: realmd
        state: present
        
#ansible_password variable is built in?   its the same as the template credential...
    - name: Join the IPA domain using the ipa-client-install command
      ansible.builtin.command: >
        ipa-client-install
        --server {{ ipa_server }}
        --domain {{ ipa_domain }}
        --principal {{ ipa_principal }}
        --password {{ ansible_password }}
        --unattended
        --mkhomedir
        --all-ip-addresses
        --ssh-trust-dns
        --no-ntp
      register: ipa_client_install_result
      changed_when: "'Client already enrolled' not in ipa_client_install_result.stdout"
