---
- name: Join IPA clients
  hosts: all
  become: true
  gather_facts: yes
  tasks: 
    - name: Configure ipaclient
      include_role:
         name: freeipa.ansible_freeipa.ipaclient
      vars:
          state: present
          ipaclient_domain: ipa.jpriddy.com
          ipaclient_dns_servers: "192.168.1.1,192.168.1.131,192.168.1.132"
          #ipaclient_use_otp: yes  #trying the otp method...
          ipaadmin_password: '{{ ansible_password }}'   #using the machine creds when i should be using a custom cred...
          ipaclient_mkhomedir: yes
          ipaclient_no_ntp: yes
          ipaclient_ssh_trust_dns: yes
          ipasssd_enable_dns_updates: yes
          ipaclient_allow_repair: yes
          ipaclient_force_join: yes
          ipaclient_cleanup_dns_resolver: yes
          ipaclient_configure_dns_resolver: yes
          ipaclient_configure_firefox: yes
    - name: Install realmd for completeness (cockpit)
      package:
        name: realmd
        state: present   