---
- name: Join IPA clients
  hosts: all
  become: true
  gather_facts: yes
  tasks: 
    - name: Deploy/configure IPA client
      include_role:
         #name: freeipa.ansible_freeipa.ipaclient
         name: redhat.rhel_idm
      vars:
          state: present
          ipaservers: "192.168.1.131"
          #ipaadmin_password: '{{ ansible_password }}'   #using the machine creds when i should be using a custom cred...
          ipaadmin_password:  '{{ ipa_password }}'  #from survey of template
          ipaclient_mkhomedir: yes
          ipaclient_no_ntp: yes
          ipaclient_ssh_trust_dns: yes
          ipaclient_allow_repair: yes
          ipaclient_force_join: yes
          ipaclient_configure_firefox: yes
          ipaclient_all_ip_addresses: yes
          #ipaclient_use_otp: yes  #doesnt work...
          #ipaclient_cleanup_dns_resolver: yes  #breaks dns
          #ipaclient_configure_dns_resolver: yes  #breaks dns
          #ipaclient_domain: ipa.jpriddy.com
          #ipaclient_dns_servers: "192.168.1.1,192.168.1.131"
          ipasssd_enable_dns_updates: yes        

    - name: Install realmd for completeness in cockpit
      package:
        name: realmd
        state: present
