---
- name: Join host to IdM domain
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    ipa_cred: "{{ lookup('ansible', 'vault', 'ipa_admin_password') }}"

  tasks:
    - name: Install IdM client package
      package:
        name: ipa-client
        state: present

    - name: Configure IdM client
      ipa_client:
        domain: ipa.jpriddy.com
        server: idm1.ipa.jpriddy.com,idm2.ipa.jpriddy.com
        principal: admin
        password: "{{ ipa_cred }}"
        force_ntp: yes
