---
- name: Set hostname of server
  hosts: all
  become: true
  tasks:

# should really not be doing a survey.. use the inventory name or dns lookup instead...


    - name: Set hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}.{{ survey_domain }}'
        use: systemd

    - name: Setup /etc/hostname
      ansible.builtin.copy:
        content: '{{ inventory_hostname }}.{{ survey_domain }}'
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'
