---
- name: Join IPA clients
  hosts: al
  become: true
  tasks:

    - name: Deploy/configure IPA client
      include_role:
        name: redhat.rhel_idm.ipaclient
      vars:
        state: present
        ipaservers: "192.168.1.131"
        ipaadmin_password: '{{ survey_ipa_password }}'
        ipaclient_mkhomedir: true
        #ipaclient_no_ntp: true
        ipaclient_ssh_trust_dns: true
        ipaclient_allow_repair: true
        ipaclient_force_join: true
        ipaclient_configure_firefox: true
        ipaclient_all_ip_addresses: true
        #ipasssd_enable_dns_updates: true

    - name: Install realmd for completeness
      ansible.builtin.package:
        name: realmd
        state: present

    - name: Create /etc/krb5.conf.d/short_hostnames.conf file
      blockinfile:
        path: /etc/krb5.conf.d/short_hostnames.conf
        block: |
          # https://web.mit.edu/kerberos/krb5-latest/doc/admin/princ_dns.html
          # so we don't need FQDNs
          rdns = true
          dns_canonicalize_hostname = fallback

    - name: Create /etc/sssd.conf.d/short_hostnames.conf file
      blockinfile:
        path: /etc/sshd.conf.d/short_hostnames.conf
        block: |
          GSSAPIStrictAcceptorCheck = no
