---
- name: Set hostname of server
  hosts: all
  become: true
  tasks:

    - name: Install python bindings so ansible will work on fedora
      ansible.builtin.package:
        name: python3-libselinux # required on fedora for ansible to work
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Set active hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}.{{ survey_domain }}'
#        name: '{{ ansible_hostname }}.{{ ansible_domain }}'
        use: systemd

    - name: Configure /etc/hostname for permanence since the hostname module can't
      ansible.builtin.copy:
        content: '{{ inventory_hostname }}.{{ survey_domain }}'
#        content: '{{ ansible_hostname }}.{{ ansible_domain }}'
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'
