---
- name: Join IPA domain
  hosts: all
  become: true
  tasks:

    - name: Deploy and configure IPA client
      include_role:
        name: redhat.rhel_idm.ipaclient
      vars:
        state: present
        ipaadmin_password: '{{ survey_ipa_password }}'
        ipaclient_mkhomedir: true
        ipaclient_ntp_servers: "192.168.1.1"
        ipaclient_ssh_trust_dns: true
        ipaclient_allow_repair: true
        ipaclient_force_join: true
        ipaclient_configure_firefox: true
        ipaclient_all_ip_addresses: true

    - name: Install realmd for completeness
      ansible.builtin.package:
        name: realmd
        state: present

    - name: Create conf file for krb5 to allow short hostnames
      copy:
        dest: "/etc/krb5.conf.d/short_hostnames.conf"
        content: |
          # https://web.mit.edu/kerberos/krb5-latest/doc/admin/princ_dns.html
          # so we don't need FQDNs
          rdns = true
          dns_canonicalize_hostname = fallback

    - name: Create conf file for sshd to allow short hostnames
      copy:
        dest: "/etc/ssh/sshd_config.d/short_hostnames.conf"
        content: |
          #https://web.mit.edu/kerberos/krb5-latest/doc/admin/princ_dns.html
          # so we don't need FQDNs
          GSSAPIStrictAcceptorCheck = no