---
- name: Join IDM domain ipa.jpriddy.com
  hosts: all
  become: yes
  vars:
    ipa_domain: ipa.jpriddy.com
    ipa_server: idm1.ipa.jpriddy.com, idm2.ipa.jpriddy.com
    ipa_user: admin
    
  tasks:
    - name: Ensure ipaclient package is installed
      package:
        name: ipa-client
        state: present

    - name: Join the IPA domain
      ansible.builtin.command: >
        ipa-client-install
        --server {{ ipa_server }}
        --domain {{ ipa_domain }}
        --principal {{ ipa_user }}
        --password {{ ansible_password }}
        --unattended
      register: ipa_client_install_result
      changed_when: "'Client already enrolled' not in ipa_client_install_result.stdout"
