---
- name: Playbook to unconfigure IPA clients
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Unconfigure ipaclient
      include_role:
        name: freeipa.ansible_freeipa.ipaclient
      vars:
        state: absent
