---
- name: Configure monitoring and metrics gathering
  hosts: all
  become: true
  tasks:

    - name: Install glances
      ansible.builtin.package:
        name: glances
        state: present

    - name: Replace glances systemd unit file with one that enables server mode
      ansible.builtin.copy:
        src: configs/glances.service
        dest: /etc/systemd/system/multi-user.target.wants/glances.service
        mode: '0644'


    - name: Enable and start glances
      ansible.builtin.systemd:
        name: glances
        daemon_reload: true
        enabled: true
        state: restarted
