---
- name: Set hostname of server based on dns
  hosts: all
  become: yes
  tasks:  
    - name: Set a hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'
        #use internal variable that is set in inventory
