---
- name: Set hostname of server 
  hosts: all
  become: yes
  tasks:  
    - name: Set a hostname
      ansible.builtin.hostname:
        name: '{{ survey_hostname }}.{{ survey_domain }}'
        #use internal variable that is set in inventory  {{ inventory_hostname }}
