---
- name: Set hostname of server based on dns
  hosts: all
  become: yes
  tasks:  
    - name: Set a hostname
      ansible.builtin.hostname:
        name: '{{ ansible_hostname }}.ipa.jpriddy.com'  ##use internal variable that is set in inventory
