---
- name: Install and start custom iperf3 systemd service for bandwith testing
  hosts: all
  become: true
  tasks:

    - name: Install iperf3
      ansible.builtin.package:
        name: iperf3
        state: present

    - name: Creating iperf3 systemd service file
      ansible.builtin.copy:
        dest: "/etc/systemd/system/iperf3.service"
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=iperf3 server
          After=syslog.target network.target auditd.service
          [Service]
          ExecStart=/usr/bin/iperf3 -s
          ExecStop=/usr/bin/killall -9 iperf3
          [Install]
          WantedBy=multi-user.target

    - name: Pick up new iperf3 service with systemd and then enable/start
      ansible.builtin.systemd:
        name: iperf3
        state: started
        daemon_reload: true
        enabled: true
