---
- name: Register with insights
  hosts: all
  become: true
  tasks:

  # need logic to ensure system has a registration, is not fedora, etc

    - name: Install and register insights client
      ansible.builtin.package:
        name: insights-client
        state: present
      ansible.builtin.command:
        cmd: insights-client --register
      when: "'RedHat' in ansible_distribution"
