---
- name: Register with insights
  hosts: all
  become: true
  tasks:
  
  #need logic to ensure system has a registration, is not fedora, etc
  
    - name: Install insights client
      ansible.builtin.package: 
        name: insights-client
        state: present

    - name: Configure insights client
      command: insights-client --register
