---
- name: Configure kdump (and reboot if necessary)
  hosts: all
  gather_facts: yes
  become: true
  tasks:

    - name: Setup kdump
      include_role:
        name: redhat.rhel_system_roles.kdump  
      vars:
      kdump_target:
          type: xfs
          location: LABEL=/
      kdump_path: /var/crash
      kdump_system_action: reboot
      kdump_reboot_ok: true
      kdump_reboot_required: true