---
- name: Configure kdump
  hosts: all
  gather_facts: yes
  become: true
  tasks:
  
  - name: Setup kdump using role
    include_role:
      name: redhat.rhel_system_roles.kdump  
    vars:
    kdump_target:
        type: xfs
        location: LABEL=/
        kdump_path: /var/crash
    kdump_system_action: reboot
    kdump_reboot_ok: false
    kdump_reboot_required: false
    
  - name: Finish up configuration using kdumpctl
    ansible.builtin.command: kdumpctl reset-crashkernel --kernel=DEFAULT
