---
- name: Configure local and remote logging
  hosts: all
  become: true
  tasks:
  
    - name: Use system role to configure journald
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.journald
      vars:
        journald_persistent: true
        journald_max_disk_size: 256
        journald_per_user: true
        journald_sync_interval: 1


    - name: Use logging role to configure rsyslog to send to remote
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.logging
      vars:
        logging_inputs:
          - name: kernel_messages_input
            type: basics
            kernel_message: true
        logging_outputs:
          - name: synology_output
            type: forwards
            #severity: info  #should default to *
            #facility: info  #should default to *
            target: 192.168.1.30
            udp_port: 514
        logging_flows:
          - name: flows0
            inputs: [kernel_messages_input]
            outputs: [fsynology_output]