---
- name: Configure logging
  hosts: all
  become: true
  tasks:
  
    - name: Use system role to configure journald
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.journald
      vars:
        journald_persistent: true
        journald_max_disk_size: 256
        journald_per_user: true
        journald_sync_interval: 1


    - name: Use system role to configure journald
      ansible.builtin.include_role:
        name: linux-system-roles.logging
      vars:
        logging_inputs:
          - name: basic_input
            type: basics
            kernel_message: true
        logging_outputs:
          - name: forward_output0
            type: forwards
            #severity: info  #should default to *
            #facility: info  #should default to *
            target: 192.168.1.30
            udp_port: 514
        logging_flows:
          - name: flows0
            inputs: [basic_input]
            outputs: [forward_output0]