#rename_this_to_cockpit

---
- name: Setup various management tooling... cockpit for now
  hosts: all
  become: true
  tasks:

    - name: Use system role to set up cockpit
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.cockpit
      vars:
        cockpit_packages:
          - cockpit-networkmanager
          - cockpit-bridge
          - cockpit-packagekit
          - cockpit-selinux
          - cockpit-storaged
          - cockpit-system
          - cockpit-ws
          - cockpit-kdump
          - cockpit-sosreport
          - cockpit-pcp
        cockpit_config:
          WebService:
            LoginTitle: "Cockpit Web Management - brought to you by Ansible and system roles"
            MaxStartups: 20
          Session:
            IdleTimeout: 15
            Banner: /etc/motd # see here: https://cockpit-project.org/faq.html#error-message-about-being-offline
        cockpit_enabled: true
        cockpit_started: true
        # cockpit_port: 9090 
        # ^^ need an offramp for redhat satellite and 
        # other services that may use 9090

# role is enabling, but not starting cockpit... so we do it here
#    - name: Start and enable cockpit
#      ansible.builtin.service:
#        name: cockpit.socket
#        enabled: true
#        state: started
