---
- name: Configure motd
  hosts: all
  gather_facts: yes
  become: true
  tasks:

  - name: Replacing /etc/motd with MOTD template
    template:
      src: templates/motd.j2
      dest: /etc/motd
        