---
- name: Configure monitoring and metrics gathering
  hosts: all
  become: true
  tasks:

    - name: Install monitoring packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - tuned
        - iftop
        - perf
        - glances
        - htop

    - name: Enable and start tuned
      ansible.builtin.service:
        name: tuned
        enabled: true
        state: started

    - name: Use system role to set up 30 days of metrics
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.metrics
      vars:
        metrics_retention_days: 31
