---
- name: Configure management and monitoring
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    
   - name: Use system role to set up cockpit
     include_role:
        name: redhat.rhel_system_roles.cockpit
     vars:
        cockpit_enabled: true
        cockpit_started: true
        cockpit_packages:
          - cockpit
          - cockpit-bridge
          - cockpit-networkmanager
          - cockpit-bridge
          - cockpit-packagekit
          - cockpit-selinux
          - cockpit-storaged
          - cockpit-system
          - cockpit-ws
          - cockpit-kdump
          - cockpit-sosreport
          - cockpit-pcp         
        cockpit_port: 9090  #need an option for satellite. 9090 is taken
        cockpit_manage_firewall: true   
        cockpit_manage_selinux: true  
        cockpit_config:                           
          WebService:                                
            LoginTitle: "Welcome to jpriddy.com" 
            MaxStartups: 20                      
          Session:                              
            IdleTimeout: 15                      
            Banner: "/etc/motd"                     
  
   - name: Use system role to set up metrics
     include_role:
        name: redhat.rhel_system_roles.metrics
     vars:
        metrics_retention_days: 31
        metrics_manage_firewall: true
       
   - name: Use system role to setup tlog
     include_role:
        name: redhat.rhel_system_roles.tlog
     vars:
        tlog_scope_sssd: all
        tlog_use_sssd: true
