#rename_this_to_cockpit

---
- name: Setup various management tools
  hosts: all
  become: true
  tasks:

    - name: Preemptively install cockpit for fedora compatibilty with rhel system role
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - cockpit # system role not installing cockpit with fedora (is there a community cockpit role?)... so we install here instead

    - name: Use system role to set up cockpit
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.cockpit
      vars:
        cockpit_packages:
          - cockpit
          - cockpit-bridge
          - cockpit-networkmanager
          - cockpit-bridge
          - cockpit-packagekit
          - cockpit-selinux
          - cockpit-storaged
          - cockpit-system
          - cockpit-ws
          - cockpit-kdump
          - cockpit-sosreport
          - cockpit-pcp
        cockpit_config:
          WebService:
            LoginTitle: "Cockpit Web Management - brought to you by Ansible and system roles"
            MaxStartups: 20
          Session:
            IdleTimeout: 15
            Banner: /etc/motd # see here for why we have these: https://cockpit-project.org/faq.html#error-message-about-being-offline
        cockpit_enabled: true
        cockpit_started: true
        # cockpit_port: 9090 #need an offramp for redhat satellite -- 9090 is taken for internal usage
        
# role is enabling, but not starting cockpit... so we do it here
    - name: Start and enable cockpit
      ansible.builtin.service:
        name: cockpit.socket
        enabled: true
        state: started
        
