- name: Mount NFS shares from 192.168.1.30
  hosts: all
  become: yes

  vars:
    nfs_mounts:
      - { name: iso, server_path: /volume2/iso }
      - { name: download, server_path: /volume1/download }
      - { name: crash, server_path: /volume2/crash }
      - { name: scratch, server_path: /volume2/scratch }
      - { name: backup, server_path: /volume2/backup }
      - { name: web, server_path: /volume2/web }
      - { name: music, server_path: /volume2/music }
      - { name: document, server_path: /volume2/document }
      - { name: video, server_path: /volume2/video }

  tasks:
    - name: Mount NFS shares
      ansible.posix.mount:
        src: "192.168.1.30:{{ item.server_path }}"
        path: "/synology/{{ item.name }}"
        fstype: nfs
        opts: "rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none,_netdev"
        state: mounted
      with_items: "{{ nfs_mounts }}"