---
- name: Install Netdata
  hosts: all
  become: true

  tasks:

    - name: Install openssl
      ansible.builtin.package:
        name: openssl
        state: present

    - name: Download the installation script from internet
      ansible.builtin.get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata_kickstart.sh
        mode: +x

    - name: Run shell command to install Netdata, then replace config file
      ansible.builtin.command: /tmp/netdata_kickstart.sh  --reinstall-even-if-unsafe --dont-wait --native-only  --stable-channel --no-updates --disable-telemetry 
      ansible.builtin.template:
        src: templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
        owner: root
        group: root
        mode: u=wrx,g=rx,o=r,+x

    - name: Restart Netdata
      ansible.builtin.service:
        name: netdata
        state: restarted
