---
- name: Install Netdata
  hosts: all
  vars_files:
    - "os_netdata_vars.yml"
  become: true

  tasks:

    - name: Install openssl
      ansible.builtin.package: 
        name: openssl
        state: latest

    - name: Download the installation script
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata_kickstart.sh
        mode: +x

    - name: Install Netdata
      command: /tmp/netdata_kickstart.sh --native-only --dont-wait  --no-updates --stable-channel --disable-telemetry

    - name: Cleanup installation script
      file:
        path: /tmp/netdata_kickstart.sh
        state: absent

    - template:
        src: templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
        owner: root
        group: root
        mode: u=wrx,g=rx,o=r,+x
      notify: Restart Netdata
      become: true

  handlers:
  - name: Restart Netdata
    service:
      name: netdata
      state: restarted