- name: Mount NFS shares from 192.168.1.30
  hosts: all
  become: yes

  vars:
    nfs_mounts:
      - { name: iso, local_path: /synology/iso, server_path: /volume2/iso }
      - { name: download, local_path: /synology/download, server_path: /volume1/download }
      - { name: crash, local_path: /var/crash, server_path: /volume2/crash }
      - { name: scratch, local_path: /synology/scratch, server_path: /volume2/scratch }
      - { name: backup, local_path: /synology/backup, server_path: /volume2/backup }
      - { name: web, local_path: /synology/web, server_path: /volume2/web }
      - { name: music, local_path: /synology/music, server_path: /volume2/music }
      - { name: document, local_path: /synology/document, server_path: /volume2/document }
      - { name: video, local_path: /synology/video, server_path: /volume2/video }

  tasks:
    - name: Mount NFS shares
      posix_mount:
        name: "{{ item.name }}"
        device: "192.168.1.30:/volume2/{{ item.server_path }}"
        dir: "{{ item.local_path }}"
        fstype: nfs
        opts: "rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none,_netdev"
        state: mounted
      with_items: "{{ nfs_mounts }}"