---
- hosts: all
  tasks:
 
 
  - name: Add rpmfusion free repo
      yum_repositoriy:
        name: rpmfusion-free
        description: “rpmfusion-free”
        file: rpmfusion
        baseurl: “http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/”
        gpgcheck: yes
        gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
        
  - name: Add rpmfusion nonfree repo
      yum_repositoriy:
        name: rpmfusion-nonfree
        description: “rpmfusion-nonfree”
        file: rpmfusion
        baseurl: “http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/os/”
        gpgcheck: yes
        gpgkey: https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020      

#fedora
#  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
#  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

#RHEL
#https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
#https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm 
#https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm

#- name: Add multiple repositories into the same file (1/2)
#  ansible.builtin.yum_repository:
#    name: epel
#    description: EPEL YUM repo
#    file: external_repos
#    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#    gpgcheck: no
#
#- name: Add multiple repositories into the same file (2/2)
#  ansible.builtin.yum_repository:
#    name: rpmforge
#    description: RPMforge YUM repo
#    file: external_repos
#    baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
#    mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
#    enabled: no
    
    
    
