---
- name: Install packages for both RHEL and Fedora
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    
    - name: (RHEL)
      dnf:
        name:
          - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-free-release-9.noarch.rpm"
          - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
        state: present
      when: ansible_distribution == 'RedHat'

    - name: (Fedora)
      dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'
