---
- name: Configure additional repos for RHEL and Fedora
  hosts: all
  become: true
  tasks:

    - name: Import gpg keys for Fedora repos
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      loop:
        - "https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        - "https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
      when: ansible_distribution == 'Fedora'
      
    - name: Install Fedora repo rpms (fusion)
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      when: ansible_distribution == 'Fedora'

#    - name: Import gpg keys for RHEL repos (fusion, epel)
#      ansible.builtin.rpm_key:
#        key: "{{ item }}"
#        state: present
#      loop:
#        - "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ansible_distribution_major_version}}"
#        - "https://download1.rpmfusion.org/free/el/RPM-GPG-KEY-rpmfusion-free-el-{{ansible_distribution_major_version}}"
#        - "https://download1.rpmfusion.org/nonfree/el/RPM-GPG-KEY-rpmfusion-nonfree-el-{{ansible_distribution_major_version}}"
#      when: ansible_distribution == 'RedHat'

#    - name: Install RHEL repo rpms (fusion, epel)
#      ansible.builtin.dnf:
#        name: "{{ item }}"
#        state: present
#      loop:
#        - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
#        - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
#        - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
#      when: ansible_distribution == 'RedHat'