- name: Set root password
  hosts: all
  become: yes
  
  tasks:
      - user:
          name: "{{ user_name }}"
          password: "{{ my_password | password_hash('sha512') }}"
        vars:
          my_password: "{{ lookup('vars', type_password|default('dynamic_password')) }}"