---
- hosts: all
  vars:
    rhc_auth:
      activation_keys:
      keys: ["rhel", "cleint-repos"]
    rhc_organization: "JPRIDDY"
    rhc_baseurl: "http://sat.ipa.jpriddy.com"
    rhc_server: "sat.ipa.jpriddy.com"
    rhc_state: present
    rhc_insights:
      autoupdate: true
      remediation: present
      state: present
    
  roles:
    - linux-system-roles.rhc