---
- name: Register to satellite
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    

- name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Server or Red Hat Virtualization
  redhat_subscription:
    state: present
    activationkey: ["rhel", "cleint-repos"]
    org_id: "JPRIDDY"
    server_hostname: "sat.ipa.jpriddy.com"
    server_insecure: enable
    
#   - name: Use system role rhc
#     include_role:
#        name: fedora.linux-system-roles.rhc
#     vars:
#      rhc_auth:
#        activation_keys:
#          keys: ["rhel", "cleint-repos"]
#      rhc_organization: "JPRIDDY"
#      rhc_baseurl: "http://sat.ipa.jpriddy.com"
#      rhc_server: "sat.ipa.jpriddy.com"
#      rhc_state: present
#      rhc_insights:
#        autoupdate: true
#        remediation: present
#        state: present