---
- name: Setup terminal logging
  hosts: all
  become: true
  tasks:
    - name: Use system role to setup terminal logging for all users
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.tlog
      vars:
        tlog_scope_sssd: all
        tlog_use_sssd: true
