---
- name: Test pulling in credentials
  hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: Fetch credential
    tower_credential:
      name: test
    register: credential_result

  - name: Use credential in task
    my_task:
      password: "{{ credential_result.credential.password }}"