---
- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: no
  tasks:
  - name: Gather facts
    community.routeros.facts:
  - ansible.builtin.debug:
      msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
  - name: Run a command
    community.routeros.command:
      commands:
       - /system resource print
         register: system_resource_print
