---
- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: no
  tasks:
  - name: Gather facts
    community.routeros.facts:
      gather_subset: all
  - name: Retrieve facts
    community.routeros.api_facts:
#  - name: Get "ip address print"
#    community.routeros.api:
#      hostname: "{{ hostname }}"
#      password: "{{ password }}"
#      username: "{{ username }}"
#      path: "ip address"
#      # The following options configure TLS/SSL.
#      # Depending on your setup, these options need different values:
#      tls: false
#      validate_certs: false
#      validate_cert_hostname: false
#  - name: Show IP address of first interface
#    ansible.builtin.debug:
#      msg: "{{ print_path.msg[0].address }}"
