- name: Update both RH and Debian based distros
  hosts: all
  become: true
  tasks:
  
  - name: Install system updates for rhel and centos
    yum:
      name: '*'
      state: latest
      update_cache: yes
      #cache_valid_time: 3600
    when:
    - ansible_os_family == "RedHat"

  - name: Install system updates for debian and ubuntu
    apt:
      name: '*'
      state: latest
      update_cache: yes
      #cache_valid_time: 3600
    when:
    - ansible_os_family == "Debian"
