---
- name: Update Plex RPM for Lifetime PlexPass Member
  hosts: media
  become: yes
  tasks:
  
    - name: Download the latest Plex RPM package
      get_url:
        url: "https://plex.tv/downloads/latest/1?channel=16&build=linux-x86_64&distro=redhat"
        dest: "/tmp/plex.rpm"
        headers:
          "X-Plex-Token": "{{ plexpass_token }}"

    - name: Install the latest Plex RPM package
      yum:
        name: "/tmp/plex.rpm"
        state: latest
        disable_gpg_check: yes

    - name: Restart the Plex service
      systemd:
        name: plexmediaserver
        state: restarted
