- name: Update both RH and Debian based distros
  hosts: all
  become: true
  tasks:
  
  - name: Install system updates for RedHat ansible OS family
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when:
    - ansible_os_family == "RedHat"

  - name: Install system updates for Debian ansible OS family
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when:
    - ansible_os_family == "Debian"
    
  - community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
    when:
    - ansible_os_family == "MacOS"
